apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  sessionAffinity: ClientIP  # Sticky sessions для WebSocket
  selector:
    app: todo     # метка в Deployment
  ports:
    - protocol: TCP
      port: 80      # порт сервиса
      targetPort: 5000  # порт контейнера